version: '3'
services:
    
    static_s:
        image: nginx
        container_name: my_nginx
        volumes:
            - ./php_for_nginx/conf/:/etc/nginx/conf.d
            - ./php/src:/usr/share/nginx
        ports:
            - "80:80"
        depends_on:
            - php-apache

    php-apache:
        container_name: my_php-apache
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/pr
            - ./php/000-default.conf:/etc/apache2/sites-available/000-default.conf
    db:
        container_name: auth_data
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: appDB
        volumes:
            - ./:/docker-entrypoint-initdb.d
            - db_volume:/var/lib/mysql
        ports:
            - "9906:3306"
volumes:
    db_volume:
