version: '3'

services:
  php:
    ports:
      - 8644:80
    build: 
      context: ./src
      dockerfile: Dockerfile
    links:
      - db
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
    ports:
      - 8705:3306

volumes:
  db_volume:
